spring.application.name=demo
membership.service.url=http://localhost:8080
heartbeat.timeout.seconds=5
spring.task.scheduling.enabled=true

# allow large multipart uploads
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
# allow large request size in embedded Tomcat
server.tomcat.max-swallow-size=50MB
